# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TemporaryExposureKeyExport.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("TemporaryExposureKeyExport.proto", :syntax => :proto2) do
    add_message "TemporaryExposureKeyExport" do
      optional :start_timestamp, :fixed64, 1
      optional :end_timestamp, :fixed64, 2
      optional :region, :string, 3
      optional :batch_num, :int32, 4
      optional :batch_size, :int32, 5
      repeated :signature_infos, :message, 6, "SignatureInfo"
      repeated :keys, :message, 7, "TemporaryExposureKey"
    end
    add_message "SignatureInfo" do
      optional :app_bundle_id, :string, 1
      optional :android_package, :string, 2
      optional :verification_key_version, :string, 3
      optional :verification_key_id, :string, 4
      optional :signature_algorithm, :string, 5
    end
    add_message "TemporaryExposureKey" do
      optional :key_data, :bytes, 1
      optional :transmission_risk_level, :int32, 2
      optional :rolling_start_interval_number, :int32, 3
      optional :rolling_period, :int32, 4, default: 144
    end
    add_message "TEKSignatureList" do
      repeated :signatures, :message, 1, "TEKSignature"
    end
    add_message "TEKSignature" do
      optional :signature_info, :message, 1, "SignatureInfo"
      optional :batch_num, :int32, 2
      optional :batch_size, :int32, 3
      optional :signature, :bytes, 4
    end
  end
end

TemporaryExposureKeyExport = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TemporaryExposureKeyExport").msgclass
SignatureInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SignatureInfo").msgclass
TemporaryExposureKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TemporaryExposureKey").msgclass
TEKSignatureList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TEKSignatureList").msgclass
TEKSignature = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TEKSignature").msgclass
